//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBolnica.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjekatBolnica.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NALOG.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sve.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Količina.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trajanje pregleda.
        /// </summary>
        public static string AppointmentDuration {
            get {
                return ResourceManager.GetString("AppointmentDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregledi.
        /// </summary>
        public static string Appointments {
            get {
                return ResourceManager.GetString("Appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazad na nalog.
        /// </summary>
        public static string BackToAcc {
            get {
                return ResourceManager.GetString("BackToAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazad na pacijente.
        /// </summary>
        public static string BackToPatients {
            get {
                return ResourceManager.GetString("BackToPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osnovne informacije.
        /// </summary>
        public static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krevet.
        /// </summary>
        public static string Bed {
            get {
                return ResourceManager.GetString("Bed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmeni lozinku.
        /// </summary>
        public static string ChangePass {
            get {
                return ResourceManager.GetString("ChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmena lozinke.
        /// </summary>
        public static string ChangePass1 {
            get {
                return ResourceManager.GetString("ChangePass1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatvori.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentar.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dan.
        /// </summary>
        public static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamna.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum i vreme.
        /// </summary>
        public static string DateAndTime {
            get {
                return ResourceManager.GetString("DateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obriši.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalji.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaz:.
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum rođenja.
        /// </summary>
        public static string DOB {
            get {
                return ResourceManager.GetString("DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum rođenja:.
        /// </summary>
        public static string DOB2 {
            get {
                return ResourceManager.GetString("DOB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lekar.
        /// </summary>
        public static string Doctor {
            get {
                return ResourceManager.GetString("Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trajanje.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Od:.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pol.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pol:.
        /// </summary>
        public static string Gender2 {
            get {
                return ResourceManager.GetString("Gender2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generiši izveštaj.
        /// </summary>
        public static string GenerateReport {
            get {
                return ResourceManager.GetString("GenerateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period hospitalizacije.
        /// </summary>
        public static string HospitalizationPeriod {
            get {
                return ResourceManager.GetString("HospitalizationPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (u minutima).
        /// </summary>
        public static string InMinutes {
            get {
                return ResourceManager.GetString("InMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime:.
        /// </summary>
        public static string LastName2 {
            get {
                return ResourceManager.GetString("LastName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svetla.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjavi se.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menadžer.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEKOVI.
        /// </summary>
        public static string Medicine {
            get {
                return ResourceManager.GetString("Medicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lekovi.
        /// </summary>
        public static string Medicines {
            get {
                return ResourceManager.GetString("Medicines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Način upotrebe.
        /// </summary>
        public static string MethodOfUse {
            get {
                return ResourceManager.GetString("MethodOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesec.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime:.
        /// </summary>
        public static string Name2 {
            get {
                return ResourceManager.GetString("Name2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv.
        /// </summary>
        public static string NazivLeka {
            get {
                return ResourceManager.GetString("NazivLeka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova lozinka.
        /// </summary>
        public static string NewPass {
            get {
                return ResourceManager.GetString("NewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obaveštenja.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordinacija.
        /// </summary>
        public static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otvori.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trajanje operacije.
        /// </summary>
        public static string OperationDuration {
            get {
                return ResourceManager.GetString("OperationDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operaciona sala.
        /// </summary>
        public static string OperationRoom {
            get {
                return ResourceManager.GetString("OperationRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operacije.
        /// </summary>
        public static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled stanja.
        /// </summary>
        public static string PastRecords {
            get {
                return ResourceManager.GetString("PastRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacijent.
        /// </summary>
        public static string Patient {
            get {
                return ResourceManager.GetString("Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacijent:.
        /// </summary>
        public static string Patient2 {
            get {
                return ResourceManager.GetString("Patient2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PACIJENTI.
        /// </summary>
        public static string Patients {
            get {
                return ResourceManager.GetString("Patients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraga pacijenata:.
        /// </summary>
        public static string PatientSearch {
            get {
                return ResourceManager.GetString("PatientSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recept.
        /// </summary>
        public static string Perscription {
            get {
                return ResourceManager.GetString("Perscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period validnosti recepta.
        /// </summary>
        public static string PerscriptionValidity {
            get {
                return ResourceManager.GetString("PerscriptionValidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj telefona.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj telefona:.
        /// </summary>
        public static string PhoneNumber2 {
            get {
                return ResourceManager.GetString("PhoneNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mere opreza.
        /// </summary>
        public static string ProtectiveMeasures {
            get {
                return ResourceManager.GetString("ProtectiveMeasures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otpusti pacijenta.
        /// </summary>
        public static string ReleasePatient {
            get {
                return ResourceManager.GetString("ReleasePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relociraj pacijenta.
        /// </summary>
        public static string RelocatePatient {
            get {
                return ResourceManager.GetString("RelocatePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ponovite lozinku.
        /// </summary>
        public static string RepeatPass {
            get {
                return ResourceManager.GetString("RepeatPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IZVEŠTAJ.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izveštaj.
        /// </summary>
        public static string Report2 {
            get {
                return ResourceManager.GetString("Report2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soba.
        /// </summary>
        public static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sačuvaj izmene.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RASPORED.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakazivanje pregleda.
        /// </summary>
        public static string ScheduleAppointment {
            get {
                return ResourceManager.GetString("ScheduleAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakazivanje operacije.
        /// </summary>
        public static string ScheduleSurgery {
            get {
                return ResourceManager.GetString("ScheduleSurgery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraga lekova:.
        /// </summary>
        public static string SearchMedicine {
            get {
                return ResourceManager.GetString("SearchMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pošiljalac.
        /// </summary>
        public static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srpski.
        /// </summary>
        public static string Serbian {
            get {
                return ResourceManager.GetString("Serbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podešavanja.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikaži.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specijalista.
        /// </summary>
        public static string Specialist {
            get {
                return ResourceManager.GetString("Specialist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uput za specijalistu.
        /// </summary>
        public static string SpecialistReferral {
            get {
                return ResourceManager.GetString("SpecialistReferral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacionarno lečenje.
        /// </summary>
        public static string StationaryTreatment {
            get {
                return ResourceManager.GetString("StationaryTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekst.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vremenski period.
        /// </summary>
        public static string TimePeriod {
            get {
                return ResourceManager.GetString("TimePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neodobreni lekovi.
        /// </summary>
        public static string UnapprovedMedicine {
            get {
                return ResourceManager.GetString("UnapprovedMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do:.
        /// </summary>
        public static string Until {
            get {
                return ResourceManager.GetString("Until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahtev za godišnji odmor.
        /// </summary>
        public static string VacationRequest {
            get {
                return ResourceManager.GetString("VacationRequest", resourceCulture);
            }
        }
    }
}
